use crate::rules::{CommandRule, FlagRule};
use crate::types::*;

pub static COMMAND_RULES: &[CommandRule] = &[
    // =====================================================================
    // Info commands (weight 0)
    // =====================================================================
    CommandRule {
        name: "ls",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "pwd",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "whoami",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1033"),
    },
    CommandRule {
        name: "hostname",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1082"),
    },
    CommandRule {
        name: "uname",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1082"),
    },
    CommandRule {
        name: "date",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "uptime",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "id",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1033"),
    },
    CommandRule {
        name: "groups",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1069"),
    },
    CommandRule {
        name: "printenv",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "echo",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "printf",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "true",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "false",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "test",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "which",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "type",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "file",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "wc",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "du",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "df",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    // =====================================================================
    // Search commands (weight 5)
    // =====================================================================
    // NOTE: for an actual `find`/`/usr/bin/find` invocation, `analyzer.rs`
    // bypasses this rule's `intent`/`reversibility`/`dangerous_flags` in
    // favor of `rules::find_fd::classify_find`, which is payload-aware:
    // `-exec`/`-execdir`/`-ok`/`-okdir`'s own command is classified and
    // folded in (see `rules/find_fd.rs`), rather than every `-exec` scoring
    // the same flat modifier regardless of whether it runs `echo` or
    // `rm -rf`. This entry (with its old flat `dangerous_flags`, now dead
    // weight for a real invocation) is retained so `lookup_command` still
    // resolves "find" and custom rules can't register a user-defined
    // "find" that would shadow it.
    CommandRule {
        name: "find",
        intent: Intent::Search,
        base_weight: 5,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[
            FlagRule {
                flags: &["-exec"],
                modifier: 30,
                risk_factor: RiskFactor::CommandExecution,
                description: "Executes a command for each matched file",
            },
            FlagRule {
                flags: &["-execdir"],
                modifier: 30,
                risk_factor: RiskFactor::CommandExecution,
                description: "Executes a command in the directory of each matched file",
            },
            FlagRule {
                flags: &["-delete"],
                modifier: 35,
                risk_factor: RiskFactor::RecursiveDelete,
                description: "Deletes matched files",
            },
        ],
        mitre: Some("T1083"),
    },
    CommandRule {
        name: "grep",
        intent: Intent::Search,
        base_weight: 5,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "rg",
        intent: Intent::Search,
        base_weight: 5,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    // NOTE: for an actual `fd`/`fdfind`/`/opt/homebrew/bin/fd` invocation,
    // `analyzer.rs` bypasses this rule's `intent`/`reversibility`/
    // `dangerous_flags` in favor of `rules::find_fd::classify_fd`, which is
    // payload-aware for `-x`/`-X`/`--exec`/`--exec-batch` (see
    // `rules/find_fd.rs`) -- previously these ran an arbitrary command per
    // match with no risk signal at all (`dangerous_flags: &[]`). This entry
    // is retained so `lookup_command` still resolves "fd" and custom rules
    // can't register a user-defined "fd" that would shadow it.
    CommandRule {
        name: "fd",
        intent: Intent::Search,
        base_weight: 5,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    // Debian/Ubuntu ship fd's binary as `fdfind` (the name `fd` is taken by
    // another package); same fallback rationale as the `fd` entry above.
    CommandRule {
        name: "fdfind",
        intent: Intent::Search,
        base_weight: 5,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "ag",
        intent: Intent::Search,
        base_weight: 5,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "locate",
        intent: Intent::Search,
        base_weight: 5,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1083"),
    },
    CommandRule {
        name: "whereis",
        intent: Intent::Search,
        base_weight: 5,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    // =====================================================================
    // Read commands (weight 10)
    // =====================================================================
    CommandRule {
        name: "cat",
        intent: Intent::Read,
        base_weight: 10,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileRead],
        dangerous_flags: &[],
        mitre: Some("T1005"),
    },
    CommandRule {
        name: "head",
        intent: Intent::Read,
        base_weight: 10,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileRead],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "tail",
        intent: Intent::Read,
        base_weight: 10,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileRead],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "less",
        intent: Intent::Read,
        base_weight: 10,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileRead, BinaryCapability::Shell],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "more",
        intent: Intent::Read,
        base_weight: 10,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileRead],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "bat",
        intent: Intent::Read,
        base_weight: 10,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileRead],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "xxd",
        intent: Intent::Read,
        base_weight: 10,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileRead],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "base64",
        intent: Intent::Read,
        base_weight: 10,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileRead],
        dangerous_flags: &[],
        mitre: Some("T1140"),
    },
    CommandRule {
        name: "strings",
        intent: Intent::Read,
        base_weight: 10,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileRead],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "hexdump",
        intent: Intent::Read,
        base_weight: 10,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileRead],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "od",
        intent: Intent::Read,
        base_weight: 10,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileRead],
        dangerous_flags: &[],
        mitre: None,
    },
    // =====================================================================
    // Write commands (weight 30)
    // =====================================================================
    CommandRule {
        name: "cp",
        intent: Intent::Write,
        base_weight: 30,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileWrite],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "mv",
        intent: Intent::Write,
        base_weight: 30,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::FileWrite],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "tee",
        intent: Intent::Write,
        base_weight: 30,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileWrite],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "touch",
        intent: Intent::Write,
        base_weight: 30,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileWrite],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "mkdir",
        intent: Intent::Write,
        base_weight: 30,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "ln",
        intent: Intent::Write,
        base_weight: 30,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileWrite],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "install",
        intent: Intent::Write,
        base_weight: 30,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileWrite],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "patch",
        intent: Intent::Write,
        base_weight: 30,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileWrite],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "sed",
        intent: Intent::Write,
        base_weight: 30,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::FileWrite],
        dangerous_flags: &[FlagRule {
            flags: &["-i"],
            modifier: 10,
            risk_factor: RiskFactor::Write,
            description: "In-place edit modifies the original file",
        }],
        mitre: None,
    },
    CommandRule {
        name: "awk",
        intent: Intent::Write,
        base_weight: 30,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileRead, BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "tar",
        intent: Intent::Write,
        base_weight: 30,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileRead, BinaryCapability::FileWrite],
        dangerous_flags: &[FlagRule {
            flags: &["--checkpoint-action=exec="],
            modifier: 40,
            risk_factor: RiskFactor::CommandExecution,
            description: "Executes arbitrary command via checkpoint action",
        }],
        mitre: Some("T1560"),
    },
    // =====================================================================
    // Delete commands (weight 45)
    // =====================================================================
    CommandRule {
        name: "rm",
        intent: Intent::Delete,
        base_weight: 45,
        reversibility: Reversibility::Irreversible,
        capabilities: &[],
        dangerous_flags: &[
            FlagRule {
                flags: &["-rf"],
                modifier: 30,
                risk_factor: RiskFactor::RecursiveDelete,
                description: "Recursive forced deletion without prompts",
            },
            FlagRule {
                flags: &["-fr"],
                modifier: 30,
                risk_factor: RiskFactor::RecursiveDelete,
                description: "Recursive forced deletion without prompts",
            },
            FlagRule {
                flags: &["--recursive", "--force"],
                modifier: 30,
                risk_factor: RiskFactor::RecursiveDelete,
                description: "Recursive forced deletion without prompts",
            },
            FlagRule {
                flags: &["--no-preserve-root"],
                modifier: 50,
                risk_factor: RiskFactor::RecursiveDelete,
                description: "Allows deletion of the root filesystem",
            },
        ],
        mitre: Some("T1485"),
    },
    CommandRule {
        name: "rmdir",
        intent: Intent::Delete,
        base_weight: 45,
        reversibility: Reversibility::Irreversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "unlink",
        intent: Intent::Delete,
        base_weight: 45,
        reversibility: Reversibility::Irreversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "shred",
        intent: Intent::Delete,
        base_weight: 45,
        reversibility: Reversibility::Irreversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1485"),
    },
    // =====================================================================
    // Execute commands (weight 50)
    // =====================================================================
    CommandRule {
        name: "bash",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Shell, BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1059.004"),
    },
    CommandRule {
        name: "sh",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Shell, BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1059.004"),
    },
    CommandRule {
        name: "zsh",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Shell, BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1059.004"),
    },
    CommandRule {
        name: "fish",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Shell, BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1059.004"),
    },
    CommandRule {
        name: "dash",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Shell, BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1059.004"),
    },
    CommandRule {
        name: "eval",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Shell, BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1059.004"),
    },
    CommandRule {
        name: "exec",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Shell, BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1059.004"),
    },
    CommandRule {
        name: "source",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Shell, BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1059.004"),
    },
    CommandRule {
        name: "python",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[
            BinaryCapability::Shell,
            BinaryCapability::Command,
            BinaryCapability::ReverseShell,
        ],
        dangerous_flags: &[],
        mitre: Some("T1059.006"),
    },
    CommandRule {
        name: "python3",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[
            BinaryCapability::Shell,
            BinaryCapability::Command,
            BinaryCapability::ReverseShell,
        ],
        dangerous_flags: &[],
        mitre: Some("T1059.006"),
    },
    CommandRule {
        name: "node",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[
            BinaryCapability::Shell,
            BinaryCapability::Command,
            BinaryCapability::ReverseShell,
        ],
        dangerous_flags: &[],
        mitre: Some("T1059.007"),
    },
    CommandRule {
        name: "deno",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Shell, BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1059.007"),
    },
    CommandRule {
        name: "bun",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Shell, BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1059.007"),
    },
    CommandRule {
        name: "ruby",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[
            BinaryCapability::Shell,
            BinaryCapability::Command,
            BinaryCapability::ReverseShell,
        ],
        dangerous_flags: &[],
        mitre: Some("T1059"),
    },
    CommandRule {
        name: "perl",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[
            BinaryCapability::Shell,
            BinaryCapability::Command,
            BinaryCapability::ReverseShell,
        ],
        dangerous_flags: &[],
        mitre: Some("T1059"),
    },
    CommandRule {
        name: "php",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[
            BinaryCapability::Shell,
            BinaryCapability::Command,
            BinaryCapability::ReverseShell,
        ],
        dangerous_flags: &[],
        mitre: Some("T1059"),
    },
    CommandRule {
        name: "lua",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Shell, BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1059"),
    },
    CommandRule {
        name: "java",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Shell, BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1059"),
    },
    // =====================================================================
    // Network commands (weight 40)
    // =====================================================================
    CommandRule {
        name: "curl",
        intent: Intent::Network,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[
            BinaryCapability::Download,
            BinaryCapability::Upload,
            BinaryCapability::Command,
        ],
        dangerous_flags: &[
            FlagRule {
                flags: &["-X", "POST"],
                modifier: 15,
                risk_factor: RiskFactor::NetworkExfiltration,
                description: "HTTP POST can exfiltrate data",
            },
            FlagRule {
                flags: &["-X", "PUT"],
                modifier: 15,
                risk_factor: RiskFactor::NetworkExfiltration,
                description: "HTTP PUT can upload data",
            },
            FlagRule {
                flags: &["-X", "DELETE"],
                modifier: 15,
                risk_factor: RiskFactor::NetworkExfiltration,
                description: "HTTP DELETE can destroy remote resources",
            },
            FlagRule {
                flags: &["-d"],
                modifier: 10,
                risk_factor: RiskFactor::NetworkExfiltration,
                description: "Sends data in request body",
            },
            FlagRule {
                flags: &["--data"],
                modifier: 10,
                risk_factor: RiskFactor::NetworkExfiltration,
                description: "Sends data in request body",
            },
            FlagRule {
                flags: &["-T"],
                modifier: 15,
                risk_factor: RiskFactor::NetworkExfiltration,
                description: "Uploads a file to a remote server",
            },
            FlagRule {
                flags: &["-o"],
                modifier: 10,
                risk_factor: RiskFactor::Write,
                description: "Writes response to a file",
            },
        ],
        mitre: Some("T1071"),
    },
    CommandRule {
        name: "wget",
        intent: Intent::Network,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Download, BinaryCapability::FileWrite],
        dangerous_flags: &[
            FlagRule {
                flags: &["--post-file"],
                modifier: 20,
                risk_factor: RiskFactor::NetworkExfiltration,
                description: "Posts file content to a remote server",
            },
            FlagRule {
                flags: &["--post-data"],
                modifier: 15,
                risk_factor: RiskFactor::NetworkExfiltration,
                description: "Posts data to a remote server",
            },
        ],
        mitre: Some("T1071"),
    },
    CommandRule {
        name: "ssh",
        intent: Intent::Network,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[
            BinaryCapability::Shell,
            BinaryCapability::Command,
            BinaryCapability::ReverseShell,
        ],
        dangerous_flags: &[
            FlagRule {
                flags: &["-R"],
                modifier: 25,
                risk_factor: RiskFactor::NetworkExfiltration,
                description: "Creates a reverse tunnel exposing local services",
            },
            FlagRule {
                flags: &["-L"],
                modifier: 15,
                risk_factor: RiskFactor::NetworkExfiltration,
                description: "Creates a local forward tunnel",
            },
        ],
        mitre: Some("T1021.004"),
    },
    CommandRule {
        name: "scp",
        intent: Intent::Network,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Upload, BinaryCapability::Download],
        dangerous_flags: &[],
        mitre: Some("T1021.004"),
    },
    CommandRule {
        name: "rsync",
        intent: Intent::Network,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[
            BinaryCapability::Upload,
            BinaryCapability::Download,
            BinaryCapability::FileWrite,
        ],
        dangerous_flags: &[],
        mitre: Some("T1105"),
    },
    CommandRule {
        name: "nc",
        intent: Intent::Network,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[
            BinaryCapability::ReverseShell,
            BinaryCapability::BindShell,
            BinaryCapability::Upload,
            BinaryCapability::Download,
        ],
        dangerous_flags: &[],
        mitre: Some("T1095"),
    },
    CommandRule {
        name: "ncat",
        intent: Intent::Network,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[
            BinaryCapability::ReverseShell,
            BinaryCapability::BindShell,
            BinaryCapability::Upload,
            BinaryCapability::Download,
        ],
        dangerous_flags: &[],
        mitre: Some("T1095"),
    },
    CommandRule {
        name: "socat",
        intent: Intent::Network,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[
            BinaryCapability::ReverseShell,
            BinaryCapability::BindShell,
            BinaryCapability::Upload,
            BinaryCapability::Download,
        ],
        dangerous_flags: &[],
        mitre: Some("T1095"),
    },
    CommandRule {
        name: "telnet",
        intent: Intent::Network,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Shell],
        dangerous_flags: &[],
        mitre: Some("T1095"),
    },
    CommandRule {
        name: "ftp",
        intent: Intent::Network,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Upload, BinaryCapability::Download],
        dangerous_flags: &[],
        mitre: Some("T1071"),
    },
    CommandRule {
        name: "sftp",
        intent: Intent::Network,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Upload, BinaryCapability::Download],
        dangerous_flags: &[],
        mitre: Some("T1071"),
    },
    CommandRule {
        name: "ping",
        intent: Intent::Network,
        base_weight: 40,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1018"),
    },
    CommandRule {
        name: "dig",
        intent: Intent::Network,
        base_weight: 40,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1018"),
    },
    CommandRule {
        name: "nslookup",
        intent: Intent::Network,
        base_weight: 40,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1018"),
    },
    CommandRule {
        name: "host",
        intent: Intent::Network,
        base_weight: 40,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1018"),
    },
    // =====================================================================
    // Process control (weight 40)
    // =====================================================================
    CommandRule {
        name: "kill",
        intent: Intent::ProcessControl,
        base_weight: 40,
        reversibility: Reversibility::Irreversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1489"),
    },
    CommandRule {
        name: "killall",
        intent: Intent::ProcessControl,
        base_weight: 40,
        reversibility: Reversibility::Irreversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1489"),
    },
    CommandRule {
        name: "pkill",
        intent: Intent::ProcessControl,
        base_weight: 40,
        reversibility: Reversibility::Irreversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1489"),
    },
    CommandRule {
        name: "nohup",
        intent: Intent::ProcessControl,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "disown",
        intent: Intent::ProcessControl,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "bg",
        intent: Intent::ProcessControl,
        base_weight: 40,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "fg",
        intent: Intent::ProcessControl,
        base_weight: 40,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "jobs",
        intent: Intent::ProcessControl,
        base_weight: 40,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "nice",
        intent: Intent::ProcessControl,
        base_weight: 40,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "renice",
        intent: Intent::ProcessControl,
        base_weight: 40,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "timeout",
        intent: Intent::ProcessControl,
        base_weight: 40,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: None,
    },
    // =====================================================================
    // Privilege commands (weight 55)
    // =====================================================================
    CommandRule {
        name: "sudo",
        intent: Intent::Privilege,
        base_weight: 55,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[
            BinaryCapability::PrivilegeEscalation,
            BinaryCapability::Shell,
            BinaryCapability::Command,
        ],
        dangerous_flags: &[],
        mitre: Some("T1548.003"),
    },
    CommandRule {
        name: "su",
        intent: Intent::Privilege,
        base_weight: 55,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[
            BinaryCapability::PrivilegeEscalation,
            BinaryCapability::Shell,
        ],
        dangerous_flags: &[],
        mitre: Some("T1548.003"),
    },
    CommandRule {
        name: "chmod",
        intent: Intent::Privilege,
        base_weight: 55,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[],
        dangerous_flags: &[
            FlagRule {
                flags: &["777"],
                modifier: 20,
                risk_factor: RiskFactor::PrivilegeEscalation,
                description: "World-readable/writable/executable permissions",
            },
            FlagRule {
                flags: &["+s"],
                modifier: 30,
                risk_factor: RiskFactor::PrivilegeEscalation,
                description: "Sets the setuid/setgid bit",
            },
            FlagRule {
                flags: &["u+s"],
                modifier: 30,
                risk_factor: RiskFactor::PrivilegeEscalation,
                description: "Sets the setuid bit for the owner",
            },
            FlagRule {
                flags: &["g+s"],
                modifier: 25,
                risk_factor: RiskFactor::PrivilegeEscalation,
                description: "Sets the setgid bit for the group",
            },
        ],
        mitre: Some("T1222"),
    },
    CommandRule {
        name: "chown",
        intent: Intent::Privilege,
        base_weight: 55,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1222"),
    },
    CommandRule {
        name: "chgrp",
        intent: Intent::Privilege,
        base_weight: 55,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1222"),
    },
    CommandRule {
        name: "chroot",
        intent: Intent::Privilege,
        base_weight: 55,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Shell, BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1548"),
    },
    CommandRule {
        name: "passwd",
        intent: Intent::Privilege,
        base_weight: 55,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1098"),
    },
    CommandRule {
        name: "useradd",
        intent: Intent::Privilege,
        base_weight: 55,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1136"),
    },
    CommandRule {
        name: "userdel",
        intent: Intent::Privilege,
        base_weight: 55,
        reversibility: Reversibility::Irreversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1531"),
    },
    CommandRule {
        name: "visudo",
        intent: Intent::Privilege,
        base_weight: 55,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1548.003"),
    },
    // =====================================================================
    // Package managers (weight 35)
    // =====================================================================
    CommandRule {
        name: "npm",
        intent: Intent::PackageInstall,
        base_weight: 35,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[
            FlagRule {
                flags: &["publish"],
                modifier: 20,
                risk_factor: RiskFactor::NetworkExfiltration,
                description: "Publishes a package to the npm registry",
            },
            FlagRule {
                flags: &["run"],
                modifier: 15,
                risk_factor: RiskFactor::CommandExecution,
                description: "Runs an arbitrary script defined in package.json",
            },
            FlagRule {
                flags: &["exec"],
                modifier: 20,
                risk_factor: RiskFactor::UntrustedExecution,
                description: "Executes a package binary, potentially downloading it first",
            },
        ],
        mitre: Some("T1195.002"),
    },
    CommandRule {
        name: "yarn",
        intent: Intent::PackageInstall,
        base_weight: 35,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1195.002"),
    },
    CommandRule {
        name: "pnpm",
        intent: Intent::PackageInstall,
        base_weight: 35,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1195.002"),
    },
    CommandRule {
        name: "pip",
        intent: Intent::PackageInstall,
        base_weight: 35,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1195.002"),
    },
    CommandRule {
        name: "pip3",
        intent: Intent::PackageInstall,
        base_weight: 35,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1195.002"),
    },
    CommandRule {
        name: "cargo",
        intent: Intent::PackageInstall,
        base_weight: 35,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1195.002"),
    },
    CommandRule {
        name: "apt",
        intent: Intent::PackageInstall,
        base_weight: 35,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1195.002"),
    },
    CommandRule {
        name: "apt-get",
        intent: Intent::PackageInstall,
        base_weight: 35,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1195.002"),
    },
    CommandRule {
        name: "brew",
        intent: Intent::PackageInstall,
        base_weight: 35,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1195.002"),
    },
    CommandRule {
        name: "gem",
        intent: Intent::PackageInstall,
        base_weight: 35,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1195.002"),
    },
    CommandRule {
        name: "go",
        intent: Intent::PackageInstall,
        base_weight: 35,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1195.002"),
    },
    // =====================================================================
    // Git (weight 35)
    // =====================================================================
    // NOTE: for an actual `git`/`/usr/bin/git` invocation, `analyzer.rs`
    // bypasses this rule's `intent`/`reversibility`/`dangerous_flags` in
    // favor of `rules::git::classify`, which is subcommand-aware (see
    // `rules/git.rs`). This entry is retained so that `lookup_command`
    // still resolves "git" (used by `RuleSet::lookup_user_command`'s
    // built-in-override check, and by the `test_rules_commands.rs` tests
    // that exercise this table directly) and so custom rules can't
    // register a user-defined "git" command that would shadow it.
    CommandRule {
        name: "git",
        intent: Intent::GitMutation,
        base_weight: 35,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[
            FlagRule {
                flags: &["push", "--force"],
                modifier: 30,
                risk_factor: RiskFactor::GitHistoryDestruction,
                description: "Force push overwrites remote branch history",
            },
            FlagRule {
                flags: &["push", "-f"],
                modifier: 30,
                risk_factor: RiskFactor::GitHistoryDestruction,
                description: "Force push overwrites remote branch history",
            },
            FlagRule {
                flags: &["push", "--force-with-lease"],
                modifier: 15,
                risk_factor: RiskFactor::GitHistoryDestruction,
                description: "Force push with lease, safer but still rewrites history",
            },
            FlagRule {
                flags: &["reset", "--hard"],
                modifier: 25,
                risk_factor: RiskFactor::GitHistoryDestruction,
                description: "Hard reset discards all uncommitted changes",
            },
            FlagRule {
                flags: &["clean", "-fd"],
                modifier: 25,
                risk_factor: RiskFactor::GitHistoryDestruction,
                description: "Removes untracked files and directories",
            },
            FlagRule {
                flags: &["clean", "-fxd"],
                modifier: 30,
                risk_factor: RiskFactor::GitHistoryDestruction,
                description: "Removes all untracked and ignored files and directories",
            },
            FlagRule {
                flags: &["checkout", "--", "."],
                modifier: 20,
                risk_factor: RiskFactor::GitHistoryDestruction,
                description: "Discards all uncommitted changes in working directory",
            },
            FlagRule {
                flags: &["branch", "-D"],
                modifier: 15,
                risk_factor: RiskFactor::GitHistoryDestruction,
                description: "Force deletes a branch regardless of merge status",
            },
        ],
        mitre: None,
    },
    // =====================================================================
    // GitHub CLI (weight 40)
    // =====================================================================
    // NOTE: for an actual `gh`/`/opt/homebrew/bin/gh` invocation,
    // `analyzer.rs` bypasses this rule's `intent`/`reversibility`/
    // `dangerous_flags` in favor of `rules::gh::classify`, which is
    // subcommand-aware (see `rules/gh.rs`). This entry is retained (with an
    // empty `dangerous_flags`, mirroring git's) so that `lookup_command`
    // still resolves "gh" and so custom rules can't register a
    // user-defined "gh" command that would shadow it. No code path scores
    // against this table directly for "gh" today, so a raw-text
    // `dangerous_flags` fallback here would be dead weight.
    CommandRule {
        name: "gh",
        intent: Intent::EnvModify,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: None,
    },
    // =====================================================================
    // Environment (weight 40)
    // =====================================================================
    CommandRule {
        name: "export",
        intent: Intent::EnvModify,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "unset",
        intent: Intent::EnvModify,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "set",
        intent: Intent::EnvModify,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "env",
        intent: Intent::EnvModify,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "alias",
        intent: Intent::EnvModify,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "declare",
        intent: Intent::EnvModify,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "typeset",
        intent: Intent::EnvModify,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    // =====================================================================
    // Container / orchestration
    // =====================================================================
    CommandRule {
        name: "docker",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[
            BinaryCapability::Shell,
            BinaryCapability::Command,
            BinaryCapability::PrivilegeEscalation,
        ],
        dangerous_flags: &[
            FlagRule {
                flags: &["run", "--privileged"],
                modifier: 35,
                risk_factor: RiskFactor::PrivilegeEscalation,
                description: "Privileged container has full host access",
            },
            FlagRule {
                flags: &["run", "-v", "/:/host"],
                modifier: 40,
                risk_factor: RiskFactor::PrivilegeEscalation,
                description: "Mounts entire host filesystem into container",
            },
        ],
        mitre: Some("T1610"),
    },
    CommandRule {
        name: "kubectl",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Shell, BinaryCapability::Command],
        dangerous_flags: &[
            FlagRule {
                flags: &["delete"],
                modifier: 25,
                risk_factor: RiskFactor::RecursiveDelete,
                description: "Deletes Kubernetes resources",
            },
            FlagRule {
                flags: &["exec"],
                modifier: 20,
                risk_factor: RiskFactor::CommandExecution,
                description: "Executes a command inside a running pod",
            },
        ],
        mitre: Some("T1609"),
    },
    // =====================================================================
    // Additional commands for completeness (sort, xargs, dd, crontab, etc.)
    // =====================================================================
    CommandRule {
        name: "xargs",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "dd",
        intent: Intent::Write,
        base_weight: 30,
        reversibility: Reversibility::Irreversible,
        capabilities: &[BinaryCapability::FileRead, BinaryCapability::FileWrite],
        dangerous_flags: &[],
        mitre: Some("T1561"),
    },
    CommandRule {
        name: "crontab",
        intent: Intent::Write,
        base_weight: 30,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1053.003"),
    },
    CommandRule {
        name: "at",
        intent: Intent::Execute,
        base_weight: 50,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1053.002"),
    },
    CommandRule {
        name: "sort",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "uniq",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "cut",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "tr",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "diff",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "ps",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1057"),
    },
    CommandRule {
        name: "top",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1057"),
    },
    CommandRule {
        name: "htop",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1057"),
    },
    CommandRule {
        name: "lsof",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1057"),
    },
    CommandRule {
        name: "netstat",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1049"),
    },
    CommandRule {
        name: "ss",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1049"),
    },
    CommandRule {
        name: "ifconfig",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1016"),
    },
    CommandRule {
        name: "ip",
        intent: Intent::Info,
        base_weight: 0,
        reversibility: Reversibility::Reversible,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1016"),
    },
    CommandRule {
        name: "mount",
        intent: Intent::Privilege,
        base_weight: 55,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "umount",
        intent: Intent::Privilege,
        base_weight: 55,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "systemctl",
        intent: Intent::ProcessControl,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1543.002"),
    },
    CommandRule {
        name: "service",
        intent: Intent::ProcessControl,
        base_weight: 40,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[BinaryCapability::Command],
        dangerous_flags: &[],
        mitre: Some("T1543.002"),
    },
    CommandRule {
        name: "iptables",
        intent: Intent::Privilege,
        base_weight: 55,
        reversibility: Reversibility::HardToReverse,
        capabilities: &[],
        dangerous_flags: &[],
        mitre: Some("T1562.004"),
    },
    CommandRule {
        name: "openssl",
        intent: Intent::Network,
        base_weight: 40,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileRead, BinaryCapability::FileWrite],
        dangerous_flags: &[],
        mitre: Some("T1573"),
    },
    CommandRule {
        name: "gpg",
        intent: Intent::Read,
        base_weight: 10,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileRead, BinaryCapability::FileWrite],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "zip",
        intent: Intent::Write,
        base_weight: 30,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileRead, BinaryCapability::FileWrite],
        dangerous_flags: &[],
        mitre: Some("T1560"),
    },
    CommandRule {
        name: "unzip",
        intent: Intent::Write,
        base_weight: 30,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileRead, BinaryCapability::FileWrite],
        dangerous_flags: &[],
        mitre: None,
    },
    CommandRule {
        name: "gzip",
        intent: Intent::Write,
        base_weight: 30,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileRead, BinaryCapability::FileWrite],
        dangerous_flags: &[],
        mitre: Some("T1560"),
    },
    CommandRule {
        name: "gunzip",
        intent: Intent::Write,
        base_weight: 30,
        reversibility: Reversibility::Reversible,
        capabilities: &[BinaryCapability::FileRead, BinaryCapability::FileWrite],
        dangerous_flags: &[],
        mitre: None,
    },
];
